version: "3.8"
services:
    php:
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/app:cached
        working_dir: /app
        container_name: unit-testing-api-php
#        extra_hosts:
#            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=unit-testing-api-php"

    unit-testing-api:
        container_name: unit-testing-api
        build:
            context: ./
            dockerfile: docker/Dockerfile
        ports:
            - '2137:2137'

